'use client';

import { useState, useEffect } from 'react';
import { api } from '@/lib/api';
import { ProjectSummary, ProjectType, FeaturePriority } from '@/types';
import { Sparkles, Check, X, Loader2, AlertCircle } from 'lucide-react';

interface TriageModalProps {
  project: ProjectSummary;
  isOpen: boolean;
  onClose: () => void;
  onConfirmed: () => void;
}

export function TriageModal({ project, isOpen, onClose, onConfirmed }: TriageModalProps) {
  const [loading, setLoading] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const [projectType, setProjectType] = useState<ProjectType>(project.project_type);
  const [goal, setGoal] = useState<string>(project.goal || '');
  const [features, setFeatures] = useState<Array<{ title: string; priority: FeaturePriority; description?: string }>>([]);
  const [providerUsed, setProviderUsed] = useState<string>('');

  useEffect(() => {
    if (isOpen) {
      fetchAITriage();
    }
  }, [isOpen]);

  const fetchAITriage = async () => {
    setLoading(true);
    setError(null);
    try {
      const res: any = await api.post(`/ai/triage/${project.id}`);
      setProjectType(res.suggested_project_type || 'RESUME');
      setGoal(res.suggested_goal || '');
      setFeatures(res.suggested_initial_features || []);
      setProviderUsed(res.provider_used || 'ai');
    } catch (err: any) {
      setError(err.message || 'Failed to fetch AI triage');
    } finally {
      setLoading(false);
    }
  };

  const handleConfirm = async () => {
    setSubmitting(true);
    setError(null);
    try {
      await api.post(`/projects/${project.id}/confirm-triage`, {
        project_type: projectType,
        goal: goal,
        initial_features: features,
      });
      onConfirmed();
      onClose();
    } catch (err: any) {
      setError(err.message || 'Failed to confirm project');
    } finally {
      setSubmitting(false);
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm p-4">
      <div className="bg-slate-900 border border-slate-800 rounded-2xl w-full max-w-2xl max-h-[90vh] overflow-y-auto shadow-2xl p-6">
        <div className="flex items-center justify-between pb-4 border-b border-slate-800 mb-5">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-indigo-600/20 text-indigo-400 flex items-center justify-center">
              <Sparkles className="w-4 h-4" />
            </div>
            <div>
              <h2 className="font-bold text-lg text-white">AI Onboarding Triage</h2>
              <p className="text-xs text-slate-400">Classify repository and set goal for <span className="text-indigo-300 font-semibold">{project.name}</span></p>
            </div>
          </div>
          <button onClick={onClose} className="p-1 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800">
            <X className="w-5 h-5" />
          </button>
        </div>

        {loading ? (
          <div className="py-16 flex flex-col items-center justify-center text-center">
            <Loader2 className="w-8 h-8 animate-spin text-indigo-500 mb-3" />
            <p className="text-sm font-semibold text-slate-200">Analyzing README & Repository Context...</p>
            <p className="text-xs text-slate-500 mt-1">Cascading through OpenRouter &rarr; Gemini &rarr; NVIDIA</p>
          </div>
        ) : (
          <div className="space-y-5">
            {error && (
              <div className="p-3 rounded-lg bg-red-950/60 border border-red-800/60 text-xs text-red-200 flex items-center gap-2">
                <AlertCircle className="w-4 h-4 text-red-400 shrink-0" />
                {error}
              </div>
            )}

            {providerUsed && (
              <div className="text-[11px] text-slate-400 flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-slate-800/40 border border-slate-800">
                <span className="w-2 h-2 rounded-full bg-emerald-400"></span>
                Classification generated by: <strong className="text-slate-200 uppercase">{providerUsed}</strong>
              </div>
            )}

            {/* Project Type Picker */}
            <div>
              <label className="block text-xs font-semibold text-slate-300 mb-2">Project Classification</label>
              <div className="grid grid-cols-3 gap-3">
                {(['COLLEGE', 'RESUME', 'PRODUCTION'] as ProjectType[]).map((t) => (
                  <button
                    key={t}
                    type="button"
                    onClick={() => setProjectType(t)}
                    className={`py-2 px-3 text-xs font-bold rounded-xl border text-center transition cursor-pointer ${
                      projectType === t
                        ? 'bg-indigo-600/20 border-indigo-500 text-indigo-300 shadow-sm'
                        : 'bg-slate-800/60 border-slate-700/60 text-slate-400 hover:bg-slate-800'
                    }`}
                  >
                    {t}
                  </button>
                ))}
              </div>
            </div>

            {/* Goal Input */}
            <div>
              <label className="block text-xs font-semibold text-slate-300 mb-1.5">Primary Target Goal</label>
              <textarea
                value={goal}
                onChange={(e) => setGoal(e.target.value)}
                rows={2}
                placeholder="What is the objective or deliverable of this project?"
                className="w-full bg-slate-800/80 border border-slate-700 rounded-xl px-3 py-2 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-indigo-500"
              />
            </div>

            {/* Proposed Initial Features */}
            <div>
              <label className="block text-xs font-semibold text-slate-300 mb-2">
                Proposed Initial MVP Features ({features.length})
              </label>
              <div className="space-y-2 max-h-48 overflow-y-auto pr-1">
                {features.map((f, i) => (
                  <div key={i} className="p-2.5 rounded-lg bg-slate-800/50 border border-slate-800 flex items-start justify-between gap-3">
                    <div>
                      <p className="text-xs font-semibold text-slate-200">{f.title}</p>
                      {f.description && <p className="text-[11px] text-slate-400 mt-0.5">{f.description}</p>}
                    </div>
                    <span className="text-[10px] font-bold px-2 py-0.5 rounded bg-indigo-950 border border-indigo-800/50 text-indigo-300 shrink-0">
                      {f.priority}
                    </span>
                  </div>
                ))}
              </div>
            </div>

            <div className="flex justify-end gap-3 pt-3 border-t border-slate-800">
              <button
                type="button"
                onClick={onClose}
                className="px-4 py-2 text-xs font-semibold rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-300"
              >
                Cancel
              </button>
              <button
                type="button"
                onClick={handleConfirm}
                disabled={submitting}
                className="px-4 py-2 text-xs font-semibold rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white flex items-center gap-1.5 disabled:opacity-50"
              >
                {submitting ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Check className="w-3.5 h-3.5" />}
                Confirm & Add Features
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
